[tool.poetry]
name = "kwc"
version = "0.1.0"
description = ""
authors = ["kiinami <kinami@posteo.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
typer = { extras = ["all"], version = "^0.9.0" }
vidgear = "^0.3.1"
peakutils = "^1.3.4"
imagehash = "^4.3.1"
opencv-python-headless = "^4.8.1.78"
python-ffmpeg = "^2.0.12"
cachier = "^3.0.0"


[tool.poetry.scripts]
kwc = "kwc.main:app"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
