[project]
name = "kwc"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachier>=3.4.1",
    "imagehash>=4.3.2",
    "opencv-python-headless>=4.12.0.88",
    "peakutils>=1.3.5",
    "pygobject>=3.52.3",
    "pygobject-stubs>=2.13.0",
    "python-ffmpeg>=2.0.12",
    "setuptools<81",
    "typer>=0.16.0",
    "vidgear>=0.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
kwc = "kwc.main:app"
